language: c++
sudo: false
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  global:
    - USE_DEB=false
    - NOT_TEST_INSTALL=true
    - USE_JENKINS=true
    - ROS_PARALLEL_JOBS='-j8'
    - CATKIN_PARALLEL_JOBS='-p8'
    - ROS_PARALLEL_TEST_JOBS='-j8'
    - CATKIN_PARALLEL_TEST_JOBS='-p8'
    - DOCKER_RUN_OPTION='--rm -e TEST_ROBOT=$TEST_ROBOT'
    - BEFORE_SCRIPT='. $CI_SOURCE_PATH/.travis.before_script.sh'
    # - ROS_REPOSITORY_PATH='http://packages.ros.org/ros/ubuntu'
    # - EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon"
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=indigo    DOCKER_RUN_OPTION='--rm -e TEST_ROBOT=pr2'   TEST_PKGS="detect_cans_in_fridge_201202 elevator_move_base_pr2 interactive_behavior_201409 jsk_2011_07_pr2_semantic jsk_2013_04_pr2_610 jsk_demo_common jsk_maps"
    - ROS_DISTRO=indigo    DOCKER_RUN_OPTION='--rm -e TEST_ROBOT=fetch' TEST_PKGS="jsk_2017_10_semi jsk_maps"
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
matrix:
  fast_finish: true
  allow_failures:
    - env: ROS_DISTRO=kinetic # need to wait for https://github.com/jsk-ros-pkg/jsk_recognition/pull/2414 and https://github.com/jsk-ros-pkg/jsk_demos/pull/1266/commits/c90dd49aeff8a4b8849787cfd57ae3bf504d3a53
    - env: ROS_DISTRO=melodic
before_script:
  - if [[ "$ROS_DISTRO" == "indigo" && "$DOCKER_IMAGE_JENKINS" == "" ]]; then export export DOCKER_IMAGE_JENKINS='ros-ubuntu:14.04-pcl'; fi
  - if [[ "$ROS_DISTRO" == "kinetic" && "$DOCKER_IMAGE_JENKINS" == "" ]]; then export export DOCKER_IMAGE_JENKINS='ros-ubuntu:16.04-pcl'; fi
  - if [[ "$ROS_DISTRO" == "melodic" && "$DOCKER_IMAGE_JENKINS" == "" ]]; then export export DOCKER_IMAGE_JENKINS='ros-ubuntu:18.04-pcl'; fi
script: source .travis/travis.sh
