Name:           ros-indigo-jsk-demo-common
Version:        0.0.3
Release:        1%{?dist}
Summary:        ROS jsk_demo_common package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/jsk_demo_common
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-control-msgs
Requires:       ros-indigo-joint-state-publisher
Requires:       ros-indigo-jsk-hark-msgs
Requires:       ros-indigo-jsk-maps
Requires:       ros-indigo-jsk-perception
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-pddl-planner
Requires:       ros-indigo-pr2-gripper-sensor-msgs
Requires:       ros-indigo-pr2-navigation-self-filter
Requires:       ros-indigo-pr2eus
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-roseus
Requires:       ros-indigo-roseus-mongo
Requires:       ros-indigo-roseus-smach
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-control-msgs
BuildRequires:  ros-indigo-jsk-hark-msgs
BuildRequires:  ros-indigo-jsk-maps
BuildRequires:  ros-indigo-jsk-perception
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-pddl-planner
BuildRequires:  ros-indigo-pr2-gripper-sensor-msgs
BuildRequires:  ros-indigo-pr2eus
BuildRequires:  ros-indigo-roseus
BuildRequires:  ros-indigo-roseus-smach

%description
The jsk_demo_common package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Feb 11 2016 Hiroyuki Mikita <mikita@jsk.imi.i.u-tokyo.ac.jp> - 0.0.3-1
- Autogenerated by Bloom

