############################################################################
##    edit this file to change setting of communication from ocs to fc    ##
############################################################################

# priodically published topic (topic transmitted through topic_buffer_server/client)
buffered_topic:

# one-shot topic (topic transmitted through topic_tools relay)
relaid_topic:
  # for teleoperation
  - /bounding_box_interactive_marker/feedback
  - /fullbody_controller/joint_trajectory_action/goal
  - /fullbody_controller/joint_trajectory_action/cancel
  - /fullbody_controller/follow_joint_trajectory_action/goal
  - /fullbody_controller/follow_joint_trajectory_action/cancel
  - /fullbody_controller/command

# service
service:
