- name: "hrp2"
  frame-id: "/hrp2_marker_root"
  robot: false
  mode: "visualization"
  # mode: "registration"
  model_param: "hrp2_urdf"
  scale: 1.0
  pose: 
    position: 
        x: 0.0
        y: 0.0
        z: 0.0
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  offset: 
    position:
        x: 0.035589
        y: 0.01
        z: -0.105
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  fixed_link:
    - "LLEG_LINK5"
    - "RLEG_LINK5"
  initial_joint_state:
    - name: "RLEG_JOINT2"
      position: -0.453786
    - name: "RLEG_JOINT3"
      position: 0.872665
    - name: "RLEG_JOINT4"
      position: -0.418879
    - name: "LLEG_JOINT2"
      position: -0.453786
    - name: "LLEG_JOINT3"
      position: 0.872665
    - name: "LLEG_JOINT4"
      position: -0.418879
    - name: "RARM_JOINT0"
      position: 0.174533
    - name: "RARM_JOINT1"
      position: -0.174533
    - name: "RARM_JOINT3"
      position: -0.436332
    - name: "RARM_JOINT6"
      position: -0.174533
    - name: "RARM_JOINT7"
      position: 0.261799
    - name: "LARM_JOINT0"
      position: 0.174533
    - name: "LARM_JOINT1"
      position: 0.174533
    - name: "LARM_JOINT3"
      position: -0.436332
    - name: "LARM_JOINT6"
      position: -0.174533
    - name: "LARM_JOINT7"
      position: -0.261799    
  display: true
