- direction: 'horizontal'
- name: 'larm only'
  service: 'larm_only_checked'
  image: "package://drc_task_common/icons/left-hand-icon.png"
  image_size: [150, 100]
  column: 0
- name: 'larm preferred'
  service: 'larm_preferred_checked'
  image: "package://drc_task_common/icons/auto-left-hand-icon.png"
  image_size: [150, 100]
  column: 0
- name: 'rarm preferred'
  service: 'rarm_preferred_checked'
  image: "package://drc_task_common/icons/auto-right-hand-icon.png"
  image_size: [150, 100]
  column: 0
  default_value: True
- name: 'rarm only'
  service: 'rarm_only_checked'
  image: "package://drc_task_common/icons/right-hand-icon.png"
  image_size: [150, 100]
  column: 0
- name: 'force overwrite stand-coords'
  service: 'force_overwrite_stand_coords'
  image: "package://drc_task_common/icons/force-overwrite-stand-coords.png"
  image_size: [100, 100]
  column: 1
- name: 'auto overwrite stand-coords'
  service: 'auto_overwrite_stand_coords'
  image: "package://drc_task_common/icons/auto-overwrite-stand-coords.png"
  image_size: [100, 100]
  column: 1
  default_value: True
- name: 'no overwrite stand-coords'
  service: 'no_overwrite_stand_coords'
  image: "package://drc_task_common/icons/no-overwrite-stand-coords.png"
  image_size: [100, 100]
  column: 1