- direction: 'horizontal'
- name: 'u1'
  service: 'dummy_u1'
  column: 0
- name: 'u2'
  service: 'dummy_u2'
  column: 0
- name: 'u3'
  service: 'dummy_u3'
  column: 0
- name: 'u4'
  service: 'dummy_u4'
  column: 0
- name: 'u5'
  service: 'dummy_u5'
  column: 0
- name: 'u6'
  service: 'dummy_u6'
  column: 0
- name: 'u7'
  service: 'dummy_u7'
  column: 0
- name: 'u8'
  service: 'dummy_u8'
  column: 0
- name: 'b1'
  service: 'dummy_b1'
  column: 1
- name: 'b2'
  service: 'dummy_b2'
  column: 1
- name: 'b3'
  service: 'dummy_b3'
  column: 1
- name: 'b4'
  service: 'dummy_b4'
  column: 1
- name: 'b5'
  service: 'dummy_b5'
  column: 1
- name: 'b6'
  service: 'dummy_b6'
  column: 1
- name: 'b7'
  service: 'dummy_b7'
  column: 1
- name: 'b8'
  service: 'dummy_b8'
  column: 1
