- direction: 'horizontal'
- name: 'reverse_grasp'
  service: 'set_handle_reverse'
  column: 0
- name: 'switch_arm'          
  service: 'switch_arm'
  column: 0
- name: 'current_pos'
  service: 'current_pos'
  column: 0
- name: 'ik_peep1'
  service: 'ik_peep1'
  column: 0
- name: 'ik_peep2'
  service: 'ik_peep2'
  column: 0
- name: 'ik_grasp'
  service: 'ik_grasp'
  column: 0