drill_param:
  multi_plane_estimate:
#    angular_threshold: 0.05
#    border_policy_ignore: true
    connect_distance_threshold: 0.01
#    connect_plane_angle_threshold: 0.2
#    depth_dependent_smoothing: false
    distance_threshold: 0.01
#    estimate_normal: true
#    estimation_method: 1 
#    max_curvature: 0.01
#    max_depth_change_factor: 0.02
#    max_refined_area_threshold: 10000.0
#    min_refined_area_threshold: 0.04
    min_size: 500
#    normal_smoothing_size: 20.0
#    publish_normal: false 
#    ransac_refine_coefficients: true
#    ransac_refine_outlier_distance_threshold: 0.1
  plane_extraction:
    max_height: 0.5
    min_height: 0.0
  euclidean_clustering:
#    label_tracking_tolerance: 0.2
#    max_size: 25000
#    min_size: 100
    tolerance: 0.02

