- name: "robot"
  frame-id: "/robot_marker_root"
  robot: false
  mode: "visualization"
  # mode: "registration"
  use_robot_description: true
  scale: 1.0
  pose: 
    position: 
        x: 0.0
        y: 0.0
        z: 0.0
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  offset: 
    position:
        x: 0.0
        y: 0.0
        z: 0.0
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  fixed_link:
    - "lleg_end_coords"
    - "rleg_end_coords"
  display: true
