- direction: 'horizontal'
- name: 'box'
  service: 'dummy_u1'
  column: 0
- name: 'cylinder'
  service: 'dummy_u2'
  column: 0
- name: 'torus'
  service: 'dummy_u3'
  column: 0
- name: 'set_pos'
  service: 'dummy_u4'
  column: 0
- name: 'go_pos'
  service: 'dummy_u5'
  column: 0
- name: 'none'
  service: 'dummy_u6'
  column: 0
- name: 'hand'
  service: 'dummy_u7'
  column: 0
- name: 'next'
  service: 'dummy_u8'
  column: 0
- name: 'approach'
  service: 'dummy_b1'
  column: 1
- name: 'mode'
  service: 'dummy_b2'
  column: 1
- name: 'object_menu'
  service: 'dummy_b3'
  column: 1
- name: 'ik'
  service: 'dummy_b4'
  column: 1
- name: 'send_angle'
  service: 'dummy_b5'
  column: 1
- name: 'robot_menu'
  service: 'dummy_b6'
  column: 1
- name: 'node'
  service: 'dummy_b7'
  column: 1
- name: 'select'
  service: 'dummy_b8'
  column: 1
