{
angular_threshold: 0.05,
border_policy_ignore: true,
connect_distance_threshold: 0.71,

connect_plane_angle_threshold: 0.0942477796077,
depth_dependent_smoothing: false,

distance_threshold: 0.1,
#estimate_normal: true,
estimation_method: 1,
max_curvature: 0.05,

max_depth_change_factor: 0.02,
max_refined_area_threshold: 10000.0,
min_refined_area_threshold: 1.0,

min_size: 100,
normal_smoothing_size: 20.0,
publish_normal: false,
ransac_refine_coefficients: true,

ransac_refine_outlier_distance_threshold: 0.1
}
